# on all hosts, run as the user ec2-user???

- name: simple mysql server setup
  hosts: db-servers:php-servers
  user: ec2-user
  sudo: True


  vars_files:
    - ./vars/sensitive_vars.yml

  # define the tasks that are part of this play...

  tasks:

  # make sure mysql is installed at the latest version

  - name: install mysql
    action: yum pkg=mysql state=latest

  # make sure php-mysql is installed at the latest version

  - name: install php-mysql
    action: yum pkg=php-mysql state=latest

  # make sure mysql-server is installed at the latest version

  - name: install python-mysqldb
    action: yum pkg=MySQL-python state=latest

  # make sure mysql-server is installed at the latest version

  - name: install mysql-server
    action: yum pkg=mysql-server state=latest

  # make sure mysqld is running
  - name: mysqld
    action: service name=mysqld state=running enabled=yes
 
  # set root passwd
  - name: Set root password
    action: mysql_user name=root password=${root_password}
    ignore_errors: True

  # make database
  - name: Create database
    action: mysql_db db=BBdb state=present login_user=root login_password=${root_password}

  # create user readonly
  - name: create db user
    action: mysql_user name=user password=${user_password} priv=*.*:SELECT  login_user=root login_password=${root_password}

  # create user for apache/php
  - name: create db user for php server
    action: mysql_user name=php_server host=ip-10-223-3-151.us-west-1.compute.internal password=${php_password} priv=*.*:ALL  login_user=root login_password=${root_password}

