# setup a phpBB server on a microinstance

- name: phpBB server setup
  hosts: web-server
  user: ec2-user
  sudo: True

  tasks:

  # return the config.php permissions to 644
 
  - name: chmod 644 config.php
    action: command chmod 0644 config.php chdir=/var/www/html/phpBB3
